// Code generated by aws/endpoints/v3model_codegen.go. DO NOT EDIT.

package endpoints

import (
	"regexp"
)

// Partition identifiers
const (
	K2PartitionID = "k2" // K2 Cloud Standard partition.
)

// K2 Cloud Standard partition's regions.
const (
	RuMskRegionID = "ru-msk" // Moscow.
	RuSpbRegionID = "ru-spb" // Saint Petersburg.
)

// DefaultResolver returns an Endpoint resolver that will be able
// to resolve endpoints for: K2 Cloud Standard.
//
// Use DefaultPartitions() to get the list of the default partitions.
func DefaultResolver() Resolver {
	return defaultPartitions
}

// DefaultPartitions returns a list of the partitions the SDK is bundled
// with. The available partitions are: K2 Cloud Standard.
//
//	partitions := endpoints.DefaultPartitions
//	for _, p := range partitions {
//	    // ... inspect partitions
//	}
func DefaultPartitions() []Partition {
	return defaultPartitions.Partitions()
}

var defaultPartitions = partitions{
	k2Partition,
}

// K2Partition returns the Resolver for K2 Cloud Standard.
func K2Partition() Partition {
	return k2Partition.Partition()
}

var k2Partition = partition{
	ID:        "k2",
	Name:      "K2 Cloud Standard",
	DNSSuffix: "k2.cloud",
	RegionRegex: regionRegex{
		Regexp: func() *regexp.Regexp {
			reg, _ := regexp.Compile("^ru-msk|ru-spb$")
			return reg
		}(),
	},
	Defaults: endpointDefaults{
		defaultKey{}: endpoint{
			Hostname:          "{service}.{region}.{dnsSuffix}",
			Protocols:         []string{"http", "https"},
			SignatureVersions: []string{"v4"},
		},
	},
	Regions: regions{
		"ru-msk": region{
			Description: "Moscow",
		},
		"ru-spb": region{
			Description: "Saint Petersburg",
		},
	},
	Services: services{
		"autoscaling": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"backup": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"cloudtrail": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"cloudwatch": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"directconnect": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"ec2": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"efs": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"eks": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"eks-legacy": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{
					Hostname: "eks.ru-msk.k2.cloud/legacy",
				},
			},
		},
		"elb": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"iam": service{
			PartitionEndpoint: "k2-global",
			IsRegionalized:    boxedFalse,
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "k2-global",
				}: endpoint{
					Hostname: "iam.k2.cloud",
					CredentialScope: credentialScope{
						Region: "ru-msk",
					},
				},
			},
		},
		"paas": service{
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
		"route53": service{
			PartitionEndpoint: "k2-global",
			IsRegionalized:    boxedFalse,
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "k2-global",
				}: endpoint{
					Hostname: "route53.k2.cloud",
					CredentialScope: credentialScope{
						Region: "ru-msk",
					},
				},
			},
		},
		"s3": service{
			Defaults: endpointDefaults{
				defaultKey{}: endpoint{
					SignatureVersions: []string{"s3v4"},
				},
			},
			Endpoints: serviceEndpoints{
				endpointKey{
					Region: "ru-msk",
				}: endpoint{},
				endpointKey{
					Region: "ru-spb",
				}: endpoint{},
			},
		},
	},
}
