// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package ekslegacy provides the client and types for making API
// requests to Amazon Elastic Kubernetes Service Legacy.
//
// Amazon EKS Legacy API provides operations that use the legacy endpoint prefix.
//
// See https://docs.aws.amazon.com/goto/WebAPI/eks-legacy-2017-11-01 for more information on this service.
//
// See ekslegacy package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/ekslegacy/
//
// # Using the Client
//
// To contact Amazon Elastic Kubernetes Service Legacy with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the Amazon Elastic Kubernetes Service Legacy client EKSLegacy for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/ekslegacy/#New
package ekslegacy
