// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package ekslegacy

import (
	"github.com/aws/aws-sdk-go/private/protocol"
)

const (

	// ErrCodeClientException for service response error code
	// "ClientException".
	//
	// These errors are usually caused by a client action. Actions can include using
	// an action or resource on behalf of a user that doesn't have permissions to
	// use the action or resource or specifying an identifier that is not valid.
	ErrCodeClientException = "ClientException"

	// ErrCodeResourceNotFoundException for service response error code
	// "ResourceNotFoundException".
	//
	// The specified resource could not be found. You can view your available clusters
	// with ListClusters. You can view your available managed node groups with ListNodegroups.
	// Amazon EKS clusters and node groups are Region-specific.
	ErrCodeResourceNotFoundException = "ResourceNotFoundException"

	// ErrCodeServerException for service response error code
	// "ServerException".
	//
	// These errors are usually caused by a server-side issue.
	ErrCodeServerException = "ServerException"

	// ErrCodeServiceUnavailableException for service response error code
	// "ServiceUnavailableException".
	//
	// The service is unavailable. Back off and retry the operation.
	ErrCodeServiceUnavailableException = "ServiceUnavailableException"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{
	"ClientException":             newErrorClientException,
	"ResourceNotFoundException":   newErrorResourceNotFoundException,
	"ServerException":             newErrorServerException,
	"ServiceUnavailableException": newErrorServiceUnavailableException,
}
