// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package paasiface provides an interface to enable mocking the AWS PaaS service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package paasiface

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/paas"
)

// PaaSAPI provides an interface to enable mocking the
// paas.PaaS service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//	// myFunc uses an SDK service client to make a request to
//	// AWS PaaS.
//	func myFunc(svc paasiface.PaaSAPI) bool {
//	    // Make svc.CreateService request
//	}
//
//	func main() {
//	    sess := session.New()
//	    svc := paas.New(sess)
//
//	    myFunc(svc)
//	}
//
// In your _test.go file:
//
//	// Define a mock struct to be used in your unit tests of myFunc.
//	type mockPaaSClient struct {
//	    paasiface.PaaSAPI
//	}
//	func (m *mockPaaSClient) CreateService(input *paas.CreateServiceInput) (*paas.CreateServiceOutput, error) {
//	    // mock response/functionality
//	}
//
//	func TestMyFunc(t *testing.T) {
//	    // Setup Test
//	    mockSvc := &mockPaaSClient{}
//
//	    myfunc(mockSvc)
//
//	    // Verify myFunc's functionality
//	}
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type PaaSAPI interface {
	CreateService(*paas.CreateServiceInput) (*paas.CreateServiceOutput, error)
	CreateServiceWithContext(aws.Context, *paas.CreateServiceInput, ...request.Option) (*paas.CreateServiceOutput, error)
	CreateServiceRequest(*paas.CreateServiceInput) (*request.Request, *paas.CreateServiceOutput)

	DeleteBackups(*paas.DeleteBackupsInput) (*paas.DeleteBackupsOutput, error)
	DeleteBackupsWithContext(aws.Context, *paas.DeleteBackupsInput, ...request.Option) (*paas.DeleteBackupsOutput, error)
	DeleteBackupsRequest(*paas.DeleteBackupsInput) (*request.Request, *paas.DeleteBackupsOutput)

	DeleteService(*paas.DeleteServiceInput) (*paas.DeleteServiceOutput, error)
	DeleteServiceWithContext(aws.Context, *paas.DeleteServiceInput, ...request.Option) (*paas.DeleteServiceOutput, error)
	DeleteServiceRequest(*paas.DeleteServiceInput) (*request.Request, *paas.DeleteServiceOutput)

	DescribeBackup(*paas.DescribeBackupInput) (*paas.DescribeBackupOutput, error)
	DescribeBackupWithContext(aws.Context, *paas.DescribeBackupInput, ...request.Option) (*paas.DescribeBackupOutput, error)
	DescribeBackupRequest(*paas.DescribeBackupInput) (*request.Request, *paas.DescribeBackupOutput)

	DescribeService(*paas.DescribeServiceInput) (*paas.DescribeServiceOutput, error)
	DescribeServiceWithContext(aws.Context, *paas.DescribeServiceInput, ...request.Option) (*paas.DescribeServiceOutput, error)
	DescribeServiceRequest(*paas.DescribeServiceInput) (*request.Request, *paas.DescribeServiceOutput)

	ListBackupUsers(*paas.ListBackupUsersInput) (*paas.ListBackupUsersOutput, error)
	ListBackupUsersWithContext(aws.Context, *paas.ListBackupUsersInput, ...request.Option) (*paas.ListBackupUsersOutput, error)
	ListBackupUsersRequest(*paas.ListBackupUsersInput) (*request.Request, *paas.ListBackupUsersOutput)

	ListBackups(*paas.ListBackupsInput) (*paas.ListBackupsOutput, error)
	ListBackupsWithContext(aws.Context, *paas.ListBackupsInput, ...request.Option) (*paas.ListBackupsOutput, error)
	ListBackupsRequest(*paas.ListBackupsInput) (*request.Request, *paas.ListBackupsOutput)

	ListServices(*paas.ListServicesInput) (*paas.ListServicesOutput, error)
	ListServicesWithContext(aws.Context, *paas.ListServicesInput, ...request.Option) (*paas.ListServicesOutput, error)
	ListServicesRequest(*paas.ListServicesInput) (*request.Request, *paas.ListServicesOutput)

	ModifyBackup(*paas.ModifyBackupInput) (*paas.ModifyBackupOutput, error)
	ModifyBackupWithContext(aws.Context, *paas.ModifyBackupInput, ...request.Option) (*paas.ModifyBackupOutput, error)
	ModifyBackupRequest(*paas.ModifyBackupInput) (*request.Request, *paas.ModifyBackupOutput)

	ModifyService(*paas.ModifyServiceInput) (*paas.ModifyServiceOutput, error)
	ModifyServiceWithContext(aws.Context, *paas.ModifyServiceInput, ...request.Option) (*paas.ModifyServiceOutput, error)
	ModifyServiceRequest(*paas.ModifyServiceInput) (*request.Request, *paas.ModifyServiceOutput)

	ModifyServiceParameters(*paas.ModifyServiceParametersInput) (*paas.ModifyServiceParametersOutput, error)
	ModifyServiceParametersWithContext(aws.Context, *paas.ModifyServiceParametersInput, ...request.Option) (*paas.ModifyServiceParametersOutput, error)
	ModifyServiceParametersRequest(*paas.ModifyServiceParametersInput) (*request.Request, *paas.ModifyServiceParametersOutput)
}

var _ PaaSAPI = (*paas.PaaS)(nil)
