name: Bump version in the provider

on:
  release:
    types:
      - published

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x

      - uses: actions/checkout@v4
        with:
          ref: develop
          repository: C2Devel/terraform-provider-rockitcloud
          token: ${{ secrets.AUTOMATION_PAT }}

      - name: Set release number
        run: |
          echo "LATEST_RELEASE=$(curl --silent https://api.github.com/repos/C2Devel/aws-sdk-go/releases/latest |\
          jq -r .name)" >> $GITHUB_ENV

      - name: Bump version in go.mod
        run: |
          go mod edit \
          -replace github.com/aws/aws-sdk-go=github.com/C2Devel/aws-sdk-go@${{ env.LATEST_RELEASE }}

      - name: Update dependencies
        run: |
          go mod tidy

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.AUTOMATION_PAT }}
          repository: C2Devel/terraform-provider-rockitcloud
          message: "modules: bump aws-sdk-go version"
          branch: "${{ env.LATEST_RELEASE }}"
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          commit-message: Update report
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: ${{ env.LATEST_RELEASE }}
          base: develop
          delete-branch: true
          title: "Bump aws-sdk-go to ${{ env.LATEST_RELEASE }}"
          body: |
            Bump aws-sdk-go to ${{ env.LATEST_RELEASE }}
            - aws-sdk-go module is updated to ${{ env.LATEST_RELEASE }}
          labels: |
            automated pr
          draft: false
  
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
          repository: C2Devel/terraform-provider-rockitcloud
