name: Bump version in the provider

on:
  release:
    types:
      - published

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x

      - uses: actions/checkout@v4
        with:
          ref: develop
          repository: C2Devel/terraform-provider-rockitcloud
          token: ${{ steps.app-token.outputs.token }}

      - name: Set release number
        run: |
          echo "LATEST_RELEASE=$(curl --silent https://api.github.com/repos/C2Devel/aws-sdk-go/releases/latest |\
          jq -r .name)" >> $GITHUB_ENV

      - name: Bump version in go.mod
        run: |
          go mod edit \
          -replace github.com/aws/aws-sdk-go=github.com/C2Devel/aws-sdk-go@${{ env.LATEST_RELEASE }}

      - name: Update dependencies
        run: |
          go mod tidy

      - name: Commit & Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add go.mod go.sum
          git commit -m "bump aws-sdk-go version to ${{ env.LATEST_RELEASE }}"
          git push origin HEAD:develop
