name: Bump version in the provider

on:
    release:
        types: [published]


jobs:
    Bump_version:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.21.x

            - uses: actions/checkout@v3
              with:
                ref: develop
                repository: vamping111/terraform-provider-rockitcloud
                token: ${{ secrets.AUTOMATION_PAT }}

            - name: Bump version in go.mod
              run: |
                go mod edit \
                -replace github.com/aws/aws-sdk-go=github.com/C2Devel/aws-sdk-go@\
                $(curl --silent https://api.github.com/repos/vamping111/aws-sdk-go/releases/latest |\
                jq -r .name)

            - name: Update dependencies
              run: |
                go mod tidy

            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                github_token: ${{ secrets.AUTOMATION_PAT }}
                repository: vamping111/terraform-provider-rockitcloud
                message: "modules: bump aws-sdk-go version"
                branch: "develop"
